/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  HierarchyNodeResponse
} from '../../model';

import {
  getGetAgentsResponseMock,
  getGetBranchesResponseMock,
  getGetDealersResponseMock
} from './organization-hierarchy-controller.faker';

export { getGetDealersResponseMock, getGetBranchesResponseMock, getGetAgentsResponseMock } from './organization-hierarchy-controller.faker';


export const getGetDealersMockHandler = (overrideResponse?: HierarchyNodeResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HierarchyNodeResponse[]> | HierarchyNodeResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/hierarchy/dealers', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDealersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetBranchesMockHandler = (overrideResponse?: HierarchyNodeResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HierarchyNodeResponse[]> | HierarchyNodeResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/hierarchy/dealers/:dealerId/branches', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetBranchesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetAgentsMockHandler = (overrideResponse?: HierarchyNodeResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HierarchyNodeResponse[]> | HierarchyNodeResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/hierarchy/branches/:branchId/agents', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAgentsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getOrganizationHierarchyControllerMock = () => [
  getGetDealersMockHandler(),
  getGetBranchesMockHandler(),
  getGetAgentsMockHandler()
]
