/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HierarchyNodeResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getDealersResponse200 = {
  data: HierarchyNodeResponse[]
  status: 200
}

export type getDealersResponseSuccess = (getDealersResponse200) & {
  headers: Headers;
};
;

export type getDealersResponse = (getDealersResponseSuccess)

export const getGetDealersUrl = () => {




  return `/api/v1/hierarchy/dealers`
}

export const getDealers = async ( options?: Parameters<typeof customInstance>[1]): Promise<getDealersResponse> => {

  return customInstance<getDealersResponse>(getGetDealersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDealersQueryKey = () => {
    return [
    `/api/v1/hierarchy/dealers`
    ] as const;
    }


export const getGetDealersQueryOptions = <TData = Awaited<ReturnType<typeof getDealers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDealersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDealers>>> = ({ signal }) => getDealers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDealers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDealersQueryResult = NonNullable<Awaited<ReturnType<typeof getDealers>>>
export type GetDealersQueryError = unknown


export function useGetDealers<TData = Awaited<ReturnType<typeof getDealers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDealers>>,
          TError,
          Awaited<ReturnType<typeof getDealers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDealers<TData = Awaited<ReturnType<typeof getDealers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDealers>>,
          TError,
          Awaited<ReturnType<typeof getDealers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDealers<TData = Awaited<ReturnType<typeof getDealers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDealers<TData = Awaited<ReturnType<typeof getDealers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDealersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getBranchesResponse200 = {
  data: HierarchyNodeResponse[]
  status: 200
}

export type getBranchesResponseSuccess = (getBranchesResponse200) & {
  headers: Headers;
};
;

export type getBranchesResponse = (getBranchesResponseSuccess)

export const getGetBranchesUrl = (dealerId: string,) => {




  return `/api/v1/hierarchy/dealers/${dealerId}/branches`
}

export const getBranches = async (dealerId: string, options?: Parameters<typeof customInstance>[1]): Promise<getBranchesResponse> => {

  return customInstance<getBranchesResponse>(getGetBranchesUrl(dealerId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBranchesQueryKey = (dealerId: string,) => {
    return [
    `/api/v1/hierarchy/dealers/${dealerId}/branches`
    ] as const;
    }


export const getGetBranchesQueryOptions = <TData = Awaited<ReturnType<typeof getBranches>>, TError = unknown>(dealerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBranchesQueryKey(dealerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBranches>>> = ({ signal }) => getBranches(dealerId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: dealerId !== null && dealerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBranches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBranchesQueryResult = NonNullable<Awaited<ReturnType<typeof getBranches>>>
export type GetBranchesQueryError = unknown


export function useGetBranches<TData = Awaited<ReturnType<typeof getBranches>>, TError = unknown>(
 dealerId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBranches>>,
          TError,
          Awaited<ReturnType<typeof getBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBranches<TData = Awaited<ReturnType<typeof getBranches>>, TError = unknown>(
 dealerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBranches>>,
          TError,
          Awaited<ReturnType<typeof getBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBranches<TData = Awaited<ReturnType<typeof getBranches>>, TError = unknown>(
 dealerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBranches<TData = Awaited<ReturnType<typeof getBranches>>, TError = unknown>(
 dealerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBranchesQueryOptions(dealerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getAgentsResponse200 = {
  data: HierarchyNodeResponse[]
  status: 200
}

export type getAgentsResponseSuccess = (getAgentsResponse200) & {
  headers: Headers;
};
;

export type getAgentsResponse = (getAgentsResponseSuccess)

export const getGetAgentsUrl = (branchId: string,) => {




  return `/api/v1/hierarchy/branches/${branchId}/agents`
}

export const getAgents = async (branchId: string, options?: Parameters<typeof customInstance>[1]): Promise<getAgentsResponse> => {

  return customInstance<getAgentsResponse>(getGetAgentsUrl(branchId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAgentsQueryKey = (branchId: string,) => {
    return [
    `/api/v1/hierarchy/branches/${branchId}/agents`
    ] as const;
    }


export const getGetAgentsQueryOptions = <TData = Awaited<ReturnType<typeof getAgents>>, TError = unknown>(branchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentsQueryKey(branchId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgents>>> = ({ signal }) => getAgents(branchId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: branchId !== null && branchId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentsQueryResult = NonNullable<Awaited<ReturnType<typeof getAgents>>>
export type GetAgentsQueryError = unknown


export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = unknown>(
 branchId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgents>>,
          TError,
          Awaited<ReturnType<typeof getAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = unknown>(
 branchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgents>>,
          TError,
          Awaited<ReturnType<typeof getAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = unknown>(
 branchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAgents<TData = Awaited<ReturnType<typeof getAgents>>, TError = unknown>(
 branchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentsQueryOptions(branchId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






