/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PagePolicyResponse,
  PolicyResponse,
  ResolvePolicy200
} from '../../model';

import {
  getCreatePolicyResponseMock,
  getGetPolicyResponseMock,
  getListPoliciesResponseMock,
  getResolvePolicyResponseMock,
  getUpdatePolicyResponseMock
} from './policy-controller.faker';

export { getListPoliciesResponseMock, getCreatePolicyResponseMock, getResolvePolicyResponseMock, getGetPolicyResponseMock, getUpdatePolicyResponseMock } from './policy-controller.faker';


export const getConfigureCommissionMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/policies/:policyId/commission', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getListPoliciesMockHandler = (overrideResponse?: PagePolicyResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PagePolicyResponse> | PagePolicyResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/policies', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPoliciesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreatePolicyMockHandler = (overrideResponse?: PolicyResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PolicyResponse> | PolicyResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/policies', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePolicyResponseMock(),
      { status: 200
      })
  }, options)
}

export const getReactivatePolicyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/policies/:policyId/lifecycle/reactivate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getDeactivatePolicyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/policies/:policyId/lifecycle/deactivate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getActivatePolicyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/policies/:policyId/lifecycle/activate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getResolvePolicyMockHandler = (overrideResponse?: ResolvePolicy200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ResolvePolicy200> | ResolvePolicy200), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/policies/resolve', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getResolvePolicyResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetPolicyMockHandler = (overrideResponse?: PolicyResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PolicyResponse> | PolicyResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/policies/:policyId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPolicyResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdatePolicyMockHandler = (overrideResponse?: PolicyResponse | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<PolicyResponse> | PolicyResponse), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/policies/:policyId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdatePolicyResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdatePremiumMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/policies/:policyId/premium', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getPolicyControllerMock = () => [
  getConfigureCommissionMockHandler(),
  getListPoliciesMockHandler(),
  getCreatePolicyMockHandler(),
  getReactivatePolicyMockHandler(),
  getDeactivatePolicyMockHandler(),
  getActivatePolicyMockHandler(),
  getResolvePolicyMockHandler(),
  getGetPolicyMockHandler(),
  getUpdatePolicyMockHandler(),
  getUpdatePremiumMockHandler()
]
