/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  IdentitySyncRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type syncProfileResponse200 = {
  data: void
  status: 200
}

export type syncProfileResponseSuccess = (syncProfileResponse200) & {
  headers: Headers;
};
;

export type syncProfileResponse = (syncProfileResponseSuccess)

export const getSyncProfileUrl = () => {




  return `/api/v1/identity/sync`
}

export const syncProfile = async (identitySyncRequest: IdentitySyncRequest, options?: Parameters<typeof customInstance>[1]): Promise<syncProfileResponse> => {

  return customInstance<syncProfileResponse>(getSyncProfileUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(identitySyncRequest)
  }
);}





export const getSyncProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncProfile>>, TError,{data: IdentitySyncRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof syncProfile>>, TError,{data: IdentitySyncRequest}, TContext> => {

const mutationKey = ['syncProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncProfile>>, {data: IdentitySyncRequest}> = (props) => {
          const {data} = props ?? {};

          return  syncProfile(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncProfileMutationResult = NonNullable<Awaited<ReturnType<typeof syncProfile>>>
    export type SyncProfileMutationBody = IdentitySyncRequest
    export type SyncProfileMutationError = unknown

    export const useSyncProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncProfile>>, TError,{data: IdentitySyncRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncProfile>>,
        TError,
        {data: IdentitySyncRequest},
        TContext
      > => {
      return useMutation(getSyncProfileMutationOptions(options), queryClient);
    }
