/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  BranchResponse,
  DealerResponse
} from '../../model';

import {
  getActivateBranchResponseMock,
  getActivateDealerResponseMock,
  getCreateBranchResponseMock,
  getCreateDealerResponseMock,
  getDeactivateBranchResponseMock,
  getDeactivateDealerResponseMock,
  getGetBranchResponseMock,
  getGetDealerResponseMock,
  getListBranchesResponseMock,
  getListDealersResponseMock,
  getUpdateBranchResponseMock,
  getUpdateDealerResponseMock
} from './organization-management-controller.faker';

export { getGetDealerResponseMock, getUpdateDealerResponseMock, getGetBranchResponseMock, getUpdateBranchResponseMock, getListDealersResponseMock, getCreateDealerResponseMock, getDeactivateDealerResponseMock, getActivateDealerResponseMock, getListBranchesResponseMock, getCreateBranchResponseMock, getDeactivateBranchResponseMock, getActivateBranchResponseMock } from './organization-management-controller.faker';


export const getGetDealerMockHandler = (overrideResponse?: DealerResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DealerResponse> | DealerResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/dealers/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDealerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateDealerMockHandler = (overrideResponse?: DealerResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<DealerResponse> | DealerResponse), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/dealers/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateDealerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetBranchMockHandler = (overrideResponse?: BranchResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BranchResponse> | BranchResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/branches/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetBranchResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateBranchMockHandler = (overrideResponse?: BranchResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<BranchResponse> | BranchResponse), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/branches/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateBranchResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListDealersMockHandler = (overrideResponse?: DealerResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DealerResponse[]> | DealerResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/dealers', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListDealersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateDealerMockHandler = (overrideResponse?: DealerResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DealerResponse> | DealerResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/dealers', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateDealerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeactivateDealerMockHandler = (overrideResponse?: DealerResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DealerResponse> | DealerResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/dealers/:id/lifecycle/deactivate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeactivateDealerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getActivateDealerMockHandler = (overrideResponse?: DealerResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DealerResponse> | DealerResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/dealers/:id/lifecycle/activate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getActivateDealerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListBranchesMockHandler = (overrideResponse?: BranchResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BranchResponse[]> | BranchResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/branches', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListBranchesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateBranchMockHandler = (overrideResponse?: BranchResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<BranchResponse> | BranchResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/branches', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateBranchResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeactivateBranchMockHandler = (overrideResponse?: BranchResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<BranchResponse> | BranchResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/branches/:id/lifecycle/deactivate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeactivateBranchResponseMock(),
      { status: 200
      })
  }, options)
}

export const getActivateBranchMockHandler = (overrideResponse?: BranchResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<BranchResponse> | BranchResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/branches/:id/lifecycle/activate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getActivateBranchResponseMock(),
      { status: 200
      })
  }, options)
}
export const getOrganizationManagementControllerMock = () => [
  getGetDealerMockHandler(),
  getUpdateDealerMockHandler(),
  getGetBranchMockHandler(),
  getUpdateBranchMockHandler(),
  getListDealersMockHandler(),
  getCreateDealerMockHandler(),
  getDeactivateDealerMockHandler(),
  getActivateDealerMockHandler(),
  getListBranchesMockHandler(),
  getCreateBranchMockHandler(),
  getDeactivateBranchMockHandler(),
  getActivateBranchMockHandler()
]
