/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BranchRequest,
  BranchResponse,
  BranchUpdateRequest,
  DealerRequest,
  DealerResponse,
  ListBranchesParams
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getDealerResponse200 = {
  data: DealerResponse
  status: 200
}

export type getDealerResponseSuccess = (getDealerResponse200) & {
  headers: Headers;
};
;

export type getDealerResponse = (getDealerResponseSuccess)

export const getGetDealerUrl = (id: string,) => {




  return `/api/v1/dealers/${id}`
}

export const getDealer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<getDealerResponse> => {

  return customInstance<getDealerResponse>(getGetDealerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDealerQueryKey = (id: string,) => {
    return [
    `/api/v1/dealers/${id}`
    ] as const;
    }


export const getGetDealerQueryOptions = <TData = Awaited<ReturnType<typeof getDealer>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDealerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDealer>>> = ({ signal }) => getDealer(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDealer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDealerQueryResult = NonNullable<Awaited<ReturnType<typeof getDealer>>>
export type GetDealerQueryError = unknown


export function useGetDealer<TData = Awaited<ReturnType<typeof getDealer>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDealer>>,
          TError,
          Awaited<ReturnType<typeof getDealer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDealer<TData = Awaited<ReturnType<typeof getDealer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDealer>>,
          TError,
          Awaited<ReturnType<typeof getDealer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDealer<TData = Awaited<ReturnType<typeof getDealer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDealer<TData = Awaited<ReturnType<typeof getDealer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDealer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDealerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateDealerResponse200 = {
  data: DealerResponse
  status: 200
}

export type updateDealerResponseSuccess = (updateDealerResponse200) & {
  headers: Headers;
};
;

export type updateDealerResponse = (updateDealerResponseSuccess)

export const getUpdateDealerUrl = (id: string,) => {




  return `/api/v1/dealers/${id}`
}

export const updateDealer = async (id: string,
    dealerRequest: DealerRequest, options?: Parameters<typeof customInstance>[1]): Promise<updateDealerResponse> => {

  return customInstance<updateDealerResponse>(getUpdateDealerUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dealerRequest)
  }
);}





export const getUpdateDealerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDealer>>, TError,{id: string;data: DealerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDealer>>, TError,{id: string;data: DealerRequest}, TContext> => {

const mutationKey = ['updateDealer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDealer>>, {id: string;data: DealerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDealer(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDealerMutationResult = NonNullable<Awaited<ReturnType<typeof updateDealer>>>
    export type UpdateDealerMutationBody = DealerRequest
    export type UpdateDealerMutationError = unknown

    export const useUpdateDealer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDealer>>, TError,{id: string;data: DealerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDealer>>,
        TError,
        {id: string;data: DealerRequest},
        TContext
      > => {
      return useMutation(getUpdateDealerMutationOptions(options), queryClient);
    }
    export type getBranchResponse200 = {
  data: BranchResponse
  status: 200
}

export type getBranchResponseSuccess = (getBranchResponse200) & {
  headers: Headers;
};
;

export type getBranchResponse = (getBranchResponseSuccess)

export const getGetBranchUrl = (id: string,) => {




  return `/api/v1/branches/${id}`
}

export const getBranch = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<getBranchResponse> => {

  return customInstance<getBranchResponse>(getGetBranchUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBranchQueryKey = (id: string,) => {
    return [
    `/api/v1/branches/${id}`
    ] as const;
    }


export const getGetBranchQueryOptions = <TData = Awaited<ReturnType<typeof getBranch>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBranchQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBranch>>> = ({ signal }) => getBranch(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBranch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBranchQueryResult = NonNullable<Awaited<ReturnType<typeof getBranch>>>
export type GetBranchQueryError = unknown


export function useGetBranch<TData = Awaited<ReturnType<typeof getBranch>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBranch>>,
          TError,
          Awaited<ReturnType<typeof getBranch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBranch<TData = Awaited<ReturnType<typeof getBranch>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBranch>>,
          TError,
          Awaited<ReturnType<typeof getBranch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBranch<TData = Awaited<ReturnType<typeof getBranch>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBranch<TData = Awaited<ReturnType<typeof getBranch>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBranch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBranchQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateBranchResponse200 = {
  data: BranchResponse
  status: 200
}

export type updateBranchResponseSuccess = (updateBranchResponse200) & {
  headers: Headers;
};
;

export type updateBranchResponse = (updateBranchResponseSuccess)

export const getUpdateBranchUrl = (id: string,) => {




  return `/api/v1/branches/${id}`
}

export const updateBranch = async (id: string,
    branchUpdateRequest: BranchUpdateRequest, options?: Parameters<typeof customInstance>[1]): Promise<updateBranchResponse> => {

  return customInstance<updateBranchResponse>(getUpdateBranchUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(branchUpdateRequest)
  }
);}





export const getUpdateBranchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBranch>>, TError,{id: string;data: BranchUpdateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBranch>>, TError,{id: string;data: BranchUpdateRequest}, TContext> => {

const mutationKey = ['updateBranch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBranch>>, {id: string;data: BranchUpdateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBranch(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateBranchMutationResult = NonNullable<Awaited<ReturnType<typeof updateBranch>>>
    export type UpdateBranchMutationBody = BranchUpdateRequest
    export type UpdateBranchMutationError = unknown

    export const useUpdateBranch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBranch>>, TError,{id: string;data: BranchUpdateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBranch>>,
        TError,
        {id: string;data: BranchUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateBranchMutationOptions(options), queryClient);
    }
    export type listDealersResponse200 = {
  data: DealerResponse[]
  status: 200
}

export type listDealersResponseSuccess = (listDealersResponse200) & {
  headers: Headers;
};
;

export type listDealersResponse = (listDealersResponseSuccess)

export const getListDealersUrl = () => {




  return `/api/v1/dealers`
}

export const listDealers = async ( options?: Parameters<typeof customInstance>[1]): Promise<listDealersResponse> => {

  return customInstance<listDealersResponse>(getListDealersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDealersQueryKey = () => {
    return [
    `/api/v1/dealers`
    ] as const;
    }


export const getListDealersQueryOptions = <TData = Awaited<ReturnType<typeof listDealers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDealers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDealersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDealers>>> = ({ signal }) => listDealers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDealers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDealersQueryResult = NonNullable<Awaited<ReturnType<typeof listDealers>>>
export type ListDealersQueryError = unknown


export function useListDealers<TData = Awaited<ReturnType<typeof listDealers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDealers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDealers>>,
          TError,
          Awaited<ReturnType<typeof listDealers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDealers<TData = Awaited<ReturnType<typeof listDealers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDealers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDealers>>,
          TError,
          Awaited<ReturnType<typeof listDealers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDealers<TData = Awaited<ReturnType<typeof listDealers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDealers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListDealers<TData = Awaited<ReturnType<typeof listDealers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDealers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDealersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createDealerResponse200 = {
  data: DealerResponse
  status: 200
}

export type createDealerResponseSuccess = (createDealerResponse200) & {
  headers: Headers;
};
;

export type createDealerResponse = (createDealerResponseSuccess)

export const getCreateDealerUrl = () => {




  return `/api/v1/dealers`
}

export const createDealer = async (dealerRequest: DealerRequest, options?: Parameters<typeof customInstance>[1]): Promise<createDealerResponse> => {

  return customInstance<createDealerResponse>(getCreateDealerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dealerRequest)
  }
);}





export const getCreateDealerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDealer>>, TError,{data: DealerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDealer>>, TError,{data: DealerRequest}, TContext> => {

const mutationKey = ['createDealer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDealer>>, {data: DealerRequest}> = (props) => {
          const {data} = props ?? {};

          return  createDealer(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDealerMutationResult = NonNullable<Awaited<ReturnType<typeof createDealer>>>
    export type CreateDealerMutationBody = DealerRequest
    export type CreateDealerMutationError = unknown

    export const useCreateDealer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDealer>>, TError,{data: DealerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDealer>>,
        TError,
        {data: DealerRequest},
        TContext
      > => {
      return useMutation(getCreateDealerMutationOptions(options), queryClient);
    }
    export type deactivateDealerResponse200 = {
  data: DealerResponse
  status: 200
}

export type deactivateDealerResponseSuccess = (deactivateDealerResponse200) & {
  headers: Headers;
};
;

export type deactivateDealerResponse = (deactivateDealerResponseSuccess)

export const getDeactivateDealerUrl = (id: string,) => {




  return `/api/v1/dealers/${id}/lifecycle/deactivate`
}

export const deactivateDealer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<deactivateDealerResponse> => {

  return customInstance<deactivateDealerResponse>(getDeactivateDealerUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivateDealerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateDealer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateDealer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deactivateDealer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateDealer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deactivateDealer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateDealerMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateDealer>>>

    export type DeactivateDealerMutationError = unknown

    export const useDeactivateDealer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateDealer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateDealer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeactivateDealerMutationOptions(options), queryClient);
    }
    export type activateDealerResponse200 = {
  data: DealerResponse
  status: 200
}

export type activateDealerResponseSuccess = (activateDealerResponse200) & {
  headers: Headers;
};
;

export type activateDealerResponse = (activateDealerResponseSuccess)

export const getActivateDealerUrl = (id: string,) => {




  return `/api/v1/dealers/${id}/lifecycle/activate`
}

export const activateDealer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<activateDealerResponse> => {

  return customInstance<activateDealerResponse>(getActivateDealerUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateDealerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateDealer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activateDealer>>, TError,{id: string}, TContext> => {

const mutationKey = ['activateDealer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateDealer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  activateDealer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateDealerMutationResult = NonNullable<Awaited<ReturnType<typeof activateDealer>>>

    export type ActivateDealerMutationError = unknown

    export const useActivateDealer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateDealer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateDealer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getActivateDealerMutationOptions(options), queryClient);
    }
    export type listBranchesResponse200 = {
  data: BranchResponse[]
  status: 200
}

export type listBranchesResponseSuccess = (listBranchesResponse200) & {
  headers: Headers;
};
;

export type listBranchesResponse = (listBranchesResponseSuccess)

export const getListBranchesUrl = (params: ListBranchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/branches?${stringifiedParams}` : `/api/v1/branches`
}

export const listBranches = async (params: ListBranchesParams, options?: Parameters<typeof customInstance>[1]): Promise<listBranchesResponse> => {

  return customInstance<listBranchesResponse>(getListBranchesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListBranchesQueryKey = (params?: ListBranchesParams,) => {
    return [
    `/api/v1/branches`, ...(params ? [params] : [])
    ] as const;
    }


export const getListBranchesQueryOptions = <TData = Awaited<ReturnType<typeof listBranches>>, TError = unknown>(params: ListBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBranches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBranchesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBranches>>> = ({ signal }) => listBranches(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBranches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBranchesQueryResult = NonNullable<Awaited<ReturnType<typeof listBranches>>>
export type ListBranchesQueryError = unknown


export function useListBranches<TData = Awaited<ReturnType<typeof listBranches>>, TError = unknown>(
 params: ListBranchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBranches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBranches>>,
          TError,
          Awaited<ReturnType<typeof listBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBranches<TData = Awaited<ReturnType<typeof listBranches>>, TError = unknown>(
 params: ListBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBranches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBranches>>,
          TError,
          Awaited<ReturnType<typeof listBranches>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBranches<TData = Awaited<ReturnType<typeof listBranches>>, TError = unknown>(
 params: ListBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBranches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListBranches<TData = Awaited<ReturnType<typeof listBranches>>, TError = unknown>(
 params: ListBranchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBranches>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBranchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createBranchResponse200 = {
  data: BranchResponse
  status: 200
}

export type createBranchResponseSuccess = (createBranchResponse200) & {
  headers: Headers;
};
;

export type createBranchResponse = (createBranchResponseSuccess)

export const getCreateBranchUrl = () => {




  return `/api/v1/branches`
}

export const createBranch = async (branchRequest: BranchRequest, options?: Parameters<typeof customInstance>[1]): Promise<createBranchResponse> => {

  return customInstance<createBranchResponse>(getCreateBranchUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(branchRequest)
  }
);}





export const getCreateBranchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBranch>>, TError,{data: BranchRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBranch>>, TError,{data: BranchRequest}, TContext> => {

const mutationKey = ['createBranch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBranch>>, {data: BranchRequest}> = (props) => {
          const {data} = props ?? {};

          return  createBranch(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateBranchMutationResult = NonNullable<Awaited<ReturnType<typeof createBranch>>>
    export type CreateBranchMutationBody = BranchRequest
    export type CreateBranchMutationError = unknown

    export const useCreateBranch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBranch>>, TError,{data: BranchRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBranch>>,
        TError,
        {data: BranchRequest},
        TContext
      > => {
      return useMutation(getCreateBranchMutationOptions(options), queryClient);
    }
    export type deactivateBranchResponse200 = {
  data: BranchResponse
  status: 200
}

export type deactivateBranchResponseSuccess = (deactivateBranchResponse200) & {
  headers: Headers;
};
;

export type deactivateBranchResponse = (deactivateBranchResponseSuccess)

export const getDeactivateBranchUrl = (id: string,) => {




  return `/api/v1/branches/${id}/lifecycle/deactivate`
}

export const deactivateBranch = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<deactivateBranchResponse> => {

  return customInstance<deactivateBranchResponse>(getDeactivateBranchUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivateBranchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateBranch>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateBranch>>, TError,{id: string}, TContext> => {

const mutationKey = ['deactivateBranch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateBranch>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deactivateBranch(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateBranchMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateBranch>>>

    export type DeactivateBranchMutationError = unknown

    export const useDeactivateBranch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateBranch>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateBranch>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeactivateBranchMutationOptions(options), queryClient);
    }
    export type activateBranchResponse200 = {
  data: BranchResponse
  status: 200
}

export type activateBranchResponseSuccess = (activateBranchResponse200) & {
  headers: Headers;
};
;

export type activateBranchResponse = (activateBranchResponseSuccess)

export const getActivateBranchUrl = (id: string,) => {




  return `/api/v1/branches/${id}/lifecycle/activate`
}

export const activateBranch = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<activateBranchResponse> => {

  return customInstance<activateBranchResponse>(getActivateBranchUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateBranchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateBranch>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activateBranch>>, TError,{id: string}, TContext> => {

const mutationKey = ['activateBranch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateBranch>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  activateBranch(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateBranchMutationResult = NonNullable<Awaited<ReturnType<typeof activateBranch>>>

    export type ActivateBranchMutationError = unknown

    export const useActivateBranch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateBranch>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateBranch>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getActivateBranchMutationOptions(options), queryClient);
    }
