/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  BranchResponse,
  DealerResponse
} from '../../model';


export const getGetDealerResponseMock = (overrideResponse: Partial<Extract<DealerResponse, object>> = {}): DealerResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getUpdateDealerResponseMock = (overrideResponse: Partial<Extract<DealerResponse, object>> = {}): DealerResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getGetBranchResponseMock = (overrideResponse: Partial<Extract<BranchResponse, object>> = {}): BranchResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dealerId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getUpdateBranchResponseMock = (overrideResponse: Partial<Extract<BranchResponse, object>> = {}): BranchResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dealerId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getListDealersResponseMock = (): DealerResponse[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined])})))

export const getCreateDealerResponseMock = (overrideResponse: Partial<Extract<DealerResponse, object>> = {}): DealerResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getDeactivateDealerResponseMock = (overrideResponse: Partial<Extract<DealerResponse, object>> = {}): DealerResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getActivateDealerResponseMock = (overrideResponse: Partial<Extract<DealerResponse, object>> = {}): DealerResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getListBranchesResponseMock = (): BranchResponse[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dealerId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined])})))

export const getCreateBranchResponseMock = (overrideResponse: Partial<Extract<BranchResponse, object>> = {}): BranchResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dealerId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getDeactivateBranchResponseMock = (overrideResponse: Partial<Extract<BranchResponse, object>> = {}): BranchResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dealerId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

export const getActivateBranchResponseMock = (overrideResponse: Partial<Extract<BranchResponse, object>> = {}): BranchResponse => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dealerId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ACTIVE','INACTIVE'] as const), undefined]), ...overrideResponse})

