/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateInsurerRequest,
  InsurerResponse,
  ListInsurersParams,
  PageInsurerResponse,
  UpdateInsurerRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getInsurerResponse200 = {
  data: InsurerResponse
  status: 200
}

export type getInsurerResponseSuccess = (getInsurerResponse200) & {
  headers: Headers;
};
;

export type getInsurerResponse = (getInsurerResponseSuccess)

export const getGetInsurerUrl = (id: string,) => {




  return `/api/v1/insurers/${id}`
}

export const getInsurer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<getInsurerResponse> => {

  return customInstance<getInsurerResponse>(getGetInsurerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInsurerQueryKey = (id: string,) => {
    return [
    `/api/v1/insurers/${id}`
    ] as const;
    }


export const getGetInsurerQueryOptions = <TData = Awaited<ReturnType<typeof getInsurer>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInsurer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInsurerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInsurer>>> = ({ signal }) => getInsurer(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInsurer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInsurerQueryResult = NonNullable<Awaited<ReturnType<typeof getInsurer>>>
export type GetInsurerQueryError = unknown


export function useGetInsurer<TData = Awaited<ReturnType<typeof getInsurer>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInsurer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInsurer>>,
          TError,
          Awaited<ReturnType<typeof getInsurer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInsurer<TData = Awaited<ReturnType<typeof getInsurer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInsurer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInsurer>>,
          TError,
          Awaited<ReturnType<typeof getInsurer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInsurer<TData = Awaited<ReturnType<typeof getInsurer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInsurer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInsurer<TData = Awaited<ReturnType<typeof getInsurer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInsurer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInsurerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateInsurerResponse200 = {
  data: InsurerResponse
  status: 200
}

export type updateInsurerResponseSuccess = (updateInsurerResponse200) & {
  headers: Headers;
};
;

export type updateInsurerResponse = (updateInsurerResponseSuccess)

export const getUpdateInsurerUrl = (id: string,) => {




  return `/api/v1/insurers/${id}`
}

export const updateInsurer = async (id: string,
    updateInsurerRequest: UpdateInsurerRequest, options?: Parameters<typeof customInstance>[1]): Promise<updateInsurerResponse> => {

  return customInstance<updateInsurerResponse>(getUpdateInsurerUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateInsurerRequest)
  }
);}





export const getUpdateInsurerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateInsurer>>, TError,{id: string;data: UpdateInsurerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateInsurer>>, TError,{id: string;data: UpdateInsurerRequest}, TContext> => {

const mutationKey = ['updateInsurer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateInsurer>>, {id: string;data: UpdateInsurerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateInsurer(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateInsurerMutationResult = NonNullable<Awaited<ReturnType<typeof updateInsurer>>>
    export type UpdateInsurerMutationBody = UpdateInsurerRequest
    export type UpdateInsurerMutationError = unknown

    export const useUpdateInsurer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateInsurer>>, TError,{id: string;data: UpdateInsurerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateInsurer>>,
        TError,
        {id: string;data: UpdateInsurerRequest},
        TContext
      > => {
      return useMutation(getUpdateInsurerMutationOptions(options), queryClient);
    }
    export type listInsurersResponse200 = {
  data: PageInsurerResponse
  status: 200
}

export type listInsurersResponseSuccess = (listInsurersResponse200) & {
  headers: Headers;
};
;

export type listInsurersResponse = (listInsurersResponseSuccess)

export const getListInsurersUrl = (params: ListInsurersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/insurers?${stringifiedParams}` : `/api/v1/insurers`
}

export const listInsurers = async (params: ListInsurersParams, options?: Parameters<typeof customInstance>[1]): Promise<listInsurersResponse> => {

  return customInstance<listInsurersResponse>(getListInsurersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListInsurersQueryKey = (params?: ListInsurersParams,) => {
    return [
    `/api/v1/insurers`, ...(params ? [params] : [])
    ] as const;
    }


export const getListInsurersQueryOptions = <TData = Awaited<ReturnType<typeof listInsurers>>, TError = unknown>(params: ListInsurersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInsurersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInsurers>>> = ({ signal }) => listInsurers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listInsurers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListInsurersQueryResult = NonNullable<Awaited<ReturnType<typeof listInsurers>>>
export type ListInsurersQueryError = unknown


export function useListInsurers<TData = Awaited<ReturnType<typeof listInsurers>>, TError = unknown>(
 params: ListInsurersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInsurers>>,
          TError,
          Awaited<ReturnType<typeof listInsurers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInsurers<TData = Awaited<ReturnType<typeof listInsurers>>, TError = unknown>(
 params: ListInsurersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInsurers>>,
          TError,
          Awaited<ReturnType<typeof listInsurers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInsurers<TData = Awaited<ReturnType<typeof listInsurers>>, TError = unknown>(
 params: ListInsurersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListInsurers<TData = Awaited<ReturnType<typeof listInsurers>>, TError = unknown>(
 params: ListInsurersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListInsurersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createInsurerResponse200 = {
  data: InsurerResponse
  status: 200
}

export type createInsurerResponseSuccess = (createInsurerResponse200) & {
  headers: Headers;
};
;

export type createInsurerResponse = (createInsurerResponseSuccess)

export const getCreateInsurerUrl = () => {




  return `/api/v1/insurers`
}

export const createInsurer = async (createInsurerRequest: CreateInsurerRequest, options?: Parameters<typeof customInstance>[1]): Promise<createInsurerResponse> => {

  return customInstance<createInsurerResponse>(getCreateInsurerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createInsurerRequest)
  }
);}





export const getCreateInsurerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInsurer>>, TError,{data: CreateInsurerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createInsurer>>, TError,{data: CreateInsurerRequest}, TContext> => {

const mutationKey = ['createInsurer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInsurer>>, {data: CreateInsurerRequest}> = (props) => {
          const {data} = props ?? {};

          return  createInsurer(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInsurerMutationResult = NonNullable<Awaited<ReturnType<typeof createInsurer>>>
    export type CreateInsurerMutationBody = CreateInsurerRequest
    export type CreateInsurerMutationError = unknown

    export const useCreateInsurer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInsurer>>, TError,{data: CreateInsurerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createInsurer>>,
        TError,
        {data: CreateInsurerRequest},
        TContext
      > => {
      return useMutation(getCreateInsurerMutationOptions(options), queryClient);
    }
    export type deactivateInsurerResponse200 = {
  data: void
  status: 200
}

export type deactivateInsurerResponseSuccess = (deactivateInsurerResponse200) & {
  headers: Headers;
};
;

export type deactivateInsurerResponse = (deactivateInsurerResponseSuccess)

export const getDeactivateInsurerUrl = (id: string,) => {




  return `/api/v1/insurers/${id}/lifecycle/deactivate`
}

export const deactivateInsurer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<deactivateInsurerResponse> => {

  return customInstance<deactivateInsurerResponse>(getDeactivateInsurerUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivateInsurerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateInsurer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateInsurer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deactivateInsurer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateInsurer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deactivateInsurer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateInsurerMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateInsurer>>>

    export type DeactivateInsurerMutationError = unknown

    export const useDeactivateInsurer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateInsurer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateInsurer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeactivateInsurerMutationOptions(options), queryClient);
    }
    export type activateInsurerResponse200 = {
  data: void
  status: 200
}

export type activateInsurerResponseSuccess = (activateInsurerResponse200) & {
  headers: Headers;
};
;

export type activateInsurerResponse = (activateInsurerResponseSuccess)

export const getActivateInsurerUrl = (id: string,) => {




  return `/api/v1/insurers/${id}/lifecycle/activate`
}

export const activateInsurer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<activateInsurerResponse> => {

  return customInstance<activateInsurerResponse>(getActivateInsurerUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateInsurerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateInsurer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activateInsurer>>, TError,{id: string}, TContext> => {

const mutationKey = ['activateInsurer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateInsurer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  activateInsurer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateInsurerMutationResult = NonNullable<Awaited<ReturnType<typeof activateInsurer>>>

    export type ActivateInsurerMutationError = unknown

    export const useActivateInsurer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateInsurer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateInsurer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getActivateInsurerMutationOptions(options), queryClient);
    }
