/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  InsurerResponse,
  PageInsurerResponse
} from '../../model';

import {
  getCreateInsurerResponseMock,
  getGetInsurerResponseMock,
  getListInsurersResponseMock,
  getUpdateInsurerResponseMock
} from './insurer-controller.faker';

export { getGetInsurerResponseMock, getUpdateInsurerResponseMock, getListInsurersResponseMock, getCreateInsurerResponseMock } from './insurer-controller.faker';


export const getGetInsurerMockHandler = (overrideResponse?: InsurerResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InsurerResponse> | InsurerResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/insurers/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetInsurerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateInsurerMockHandler = (overrideResponse?: InsurerResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<InsurerResponse> | InsurerResponse), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/insurers/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateInsurerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListInsurersMockHandler = (overrideResponse?: PageInsurerResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PageInsurerResponse> | PageInsurerResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/insurers', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListInsurersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateInsurerMockHandler = (overrideResponse?: InsurerResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<InsurerResponse> | InsurerResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/insurers', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateInsurerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeactivateInsurerMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/insurers/:id/lifecycle/deactivate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getActivateInsurerMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/insurers/:id/lifecycle/activate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getInsurerControllerMock = () => [
  getGetInsurerMockHandler(),
  getUpdateInsurerMockHandler(),
  getListInsurersMockHandler(),
  getCreateInsurerMockHandler(),
  getDeactivateInsurerMockHandler(),
  getActivateInsurerMockHandler()
]
