/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  CommissionStatisticsResponse,
  PolicyStatisticsResponse
} from '../../model';


export const getGetPolicyStatisticsResponseMock = (overrideResponse: Partial<Extract<PolicyStatisticsResponse, object>> = {}): PolicyStatisticsResponse => ({totalPolicies: faker.helpers.arrayElement([faker.number.int(), undefined]), draftCount: faker.helpers.arrayElement([faker.number.int(), undefined]), activeCount: faker.helpers.arrayElement([faker.number.int(), undefined]), inactiveCount: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getGetCommissionStatisticsResponseMock = (overrideResponse: Partial<Extract<CommissionStatisticsResponse, object>> = {}): CommissionStatisticsResponse => ({totalCommissionAmount: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), agentACommissionAmount: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), agentBCommissionAmount: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), configuredCommissionCount: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

