/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommissionStatisticsResponse,
  PolicyStatisticsResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPolicyStatisticsResponse200 = {
  data: PolicyStatisticsResponse
  status: 200
}

export type getPolicyStatisticsResponseSuccess = (getPolicyStatisticsResponse200) & {
  headers: Headers;
};
;

export type getPolicyStatisticsResponse = (getPolicyStatisticsResponseSuccess)

export const getGetPolicyStatisticsUrl = () => {




  return `/api/v1/reporting/policies/statistics`
}

export const getPolicyStatistics = async ( options?: RequestInit): Promise<getPolicyStatisticsResponse> => {

  return customInstance<getPolicyStatisticsResponse>(getGetPolicyStatisticsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPolicyStatisticsQueryKey = () => {
    return [
    `/api/v1/reporting/policies/statistics`
    ] as const;
    }


export const getGetPolicyStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getPolicyStatistics>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyStatistics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPolicyStatisticsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicyStatistics>>> = ({ signal }) => getPolicyStatistics({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPolicyStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPolicyStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getPolicyStatistics>>>
export type GetPolicyStatisticsQueryError = unknown


export function useGetPolicyStatistics<TData = Awaited<ReturnType<typeof getPolicyStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyStatistics>>,
          TError,
          Awaited<ReturnType<typeof getPolicyStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPolicyStatistics<TData = Awaited<ReturnType<typeof getPolicyStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyStatistics>>,
          TError,
          Awaited<ReturnType<typeof getPolicyStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPolicyStatistics<TData = Awaited<ReturnType<typeof getPolicyStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPolicyStatistics<TData = Awaited<ReturnType<typeof getPolicyStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPolicyStatisticsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCommissionStatisticsResponse200 = {
  data: CommissionStatisticsResponse
  status: 200
}

export type getCommissionStatisticsResponseSuccess = (getCommissionStatisticsResponse200) & {
  headers: Headers;
};
;

export type getCommissionStatisticsResponse = (getCommissionStatisticsResponseSuccess)

export const getGetCommissionStatisticsUrl = () => {




  return `/api/v1/reporting/commissions/statistics`
}

export const getCommissionStatistics = async ( options?: RequestInit): Promise<getCommissionStatisticsResponse> => {

  return customInstance<getCommissionStatisticsResponse>(getGetCommissionStatisticsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCommissionStatisticsQueryKey = () => {
    return [
    `/api/v1/reporting/commissions/statistics`
    ] as const;
    }


export const getGetCommissionStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getCommissionStatistics>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionStatistics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommissionStatisticsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommissionStatistics>>> = ({ signal }) => getCommissionStatistics({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCommissionStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommissionStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getCommissionStatistics>>>
export type GetCommissionStatisticsQueryError = unknown


export function useGetCommissionStatistics<TData = Awaited<ReturnType<typeof getCommissionStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommissionStatistics>>,
          TError,
          Awaited<ReturnType<typeof getCommissionStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommissionStatistics<TData = Awaited<ReturnType<typeof getCommissionStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommissionStatistics>>,
          TError,
          Awaited<ReturnType<typeof getCommissionStatistics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommissionStatistics<TData = Awaited<ReturnType<typeof getCommissionStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCommissionStatistics<TData = Awaited<ReturnType<typeof getCommissionStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionStatistics>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCommissionStatisticsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






