/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CommissionStatisticsResponse,
  PolicyStatisticsResponse
} from '../../model';

import {
  getGetCommissionStatisticsResponseMock,
  getGetPolicyStatisticsResponseMock
} from './reporting-controller.faker';

export { getGetPolicyStatisticsResponseMock, getGetCommissionStatisticsResponseMock } from './reporting-controller.faker';


export const getGetPolicyStatisticsMockHandler = (overrideResponse?: PolicyStatisticsResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PolicyStatisticsResponse> | PolicyStatisticsResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/reporting/policies/statistics', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPolicyStatisticsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetCommissionStatisticsMockHandler = (overrideResponse?: CommissionStatisticsResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CommissionStatisticsResponse> | CommissionStatisticsResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/reporting/commissions/statistics', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCommissionStatisticsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getReportingControllerMock = () => [
  getGetPolicyStatisticsMockHandler(),
  getGetCommissionStatisticsMockHandler()
]
