/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateCustomerRequestCustomerType } from './createCustomerRequestCustomerType';

export interface CreateCustomerRequest {
  customerType: CreateCustomerRequestCustomerType;
  name: string;
  contactInfo: string;
  addressInfo: string;
  individualInfo?: string;
  businessInfo?: string;
  targetDealerId?: string;
  targetBranchId?: string;
  targetAgentId?: string;
}
