/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreatePolicyRequest {
  policyNumber?: string;
  customerId?: string;
  insurerId?: string;
  agentAId?: string;
  agentBId?: string;
  branchId?: string;
}
