/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateCustomerRequestCustomerType = typeof CreateCustomerRequestCustomerType[keyof typeof CreateCustomerRequestCustomerType];


export const CreateCustomerRequestCustomerType = {
  INDIVIDUAL: 'INDIVIDUAL',
  ORGANIZATION: 'ORGANIZATION',
} as const;
