/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CustomerResponse {
  id?: string;
  customerType?: string;
  name?: string;
  contactInfo?: string;
  addressInfo?: string;
  status?: string;
  individualInfo?: string;
  businessInfo?: string;
  createdAt?: string;
  updatedAt?: string;
}
