/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Pageable } from './pageable';

export type ListProductsParams = {
name?: string;
category?: string;
status?: string;
pageable: Pageable;
};
