/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { InsurerResponse } from './insurerResponse';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface PageInsurerResponse {
  totalElements?: number;
  totalPages?: number;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  pageable?: PageableObject;
  size?: number;
  content?: InsurerResponse[];
  number?: number;
  sort?: SortObject[];
  empty?: boolean;
}
