/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageableObject } from './pageableObject';
import type { PolicyResponse } from './policyResponse';
import type { SortObject } from './sortObject';

export interface PagePolicyResponse {
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  content?: PolicyResponse[];
  number?: number;
  sort?: SortObject[];
  empty?: boolean;
}
