/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CustomerResponse } from './customerResponse';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface PageCustomerResponse {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  content?: CustomerResponse[];
  number?: number;
  sort?: SortObject[];
  empty?: boolean;
}
