/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PolicyResponse {
  policyId?: string;
  policyNumber?: string;
  customerId?: string;
  insurerId?: string;
  agentAId?: string;
  agentBId?: string;
  branchId?: string;
  premium?: number;
  status?: string;
}
