/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PolicyDocumentResponse {
  policyId?: string;
  originalFilename?: string;
  contentType?: string;
  sizeBytes?: number;
  downloadUrl?: string;
}
