/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PolicyStatisticsResponse {
  totalPolicies?: number;
  draftCount?: number;
  activeCount?: number;
  inactiveCount?: number;
}
