/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateCustomerRequest {
  name: string;
  contactInfo: string;
  addressInfo: string;
  individualInfo?: string;
  businessInfo?: string;
}
