/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PolicyDocumentResponse,
  PresignedUploadResponse
} from '../../model';

import {
  getGenerateUploadUrlResponseMock,
  getGetDocumentResponseMock,
  getRegisterDocumentResponseMock
} from './policy-document-controller.faker';

export { getGetDocumentResponseMock, getRegisterDocumentResponseMock, getGenerateUploadUrlResponseMock } from './policy-document-controller.faker';


export const getGetDocumentMockHandler = (overrideResponse?: PolicyDocumentResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PolicyDocumentResponse> | PolicyDocumentResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/policies/:policyId/document', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDocumentResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRegisterDocumentMockHandler = (overrideResponse?: PolicyDocumentResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PolicyDocumentResponse> | PolicyDocumentResponse), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/policies/:policyId/document', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRegisterDocumentResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteDocumentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/policies/:policyId/document', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGenerateUploadUrlMockHandler = (overrideResponse?: PresignedUploadResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PresignedUploadResponse> | PresignedUploadResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/policies/:policyId/document/presigned-upload', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGenerateUploadUrlResponseMock(),
      { status: 200
      })
  }, options)
}
export const getPolicyDocumentControllerMock = () => [
  getGetDocumentMockHandler(),
  getRegisterDocumentMockHandler(),
  getDeleteDocumentMockHandler(),
  getGenerateUploadUrlMockHandler()
]
