/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PolicyDocumentResponse,
  PresignedUploadRequest,
  PresignedUploadResponse,
  RegisterPolicyDocumentRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getDocumentResponse200 = {
  data: PolicyDocumentResponse
  status: 200
}

export type getDocumentResponseSuccess = (getDocumentResponse200) & {
  headers: Headers;
};
;

export type getDocumentResponse = (getDocumentResponseSuccess)

export const getGetDocumentUrl = (policyId: string,) => {




  return `/api/v1/policies/${policyId}/document`
}

export const getDocument = async (policyId: string, options?: Parameters<typeof customInstance>[1]): Promise<getDocumentResponse> => {

  return customInstance<getDocumentResponse>(getGetDocumentUrl(policyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDocumentQueryKey = (policyId: string,) => {
    return [
    `/api/v1/policies/${policyId}/document`
    ] as const;
    }


export const getGetDocumentQueryOptions = <TData = Awaited<ReturnType<typeof getDocument>>, TError = unknown>(policyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentQueryKey(policyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocument>>> = ({ signal }) => getDocument(policyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: policyId !== null && policyId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof getDocument>>>
export type GetDocumentQueryError = unknown


export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = unknown>(
 policyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = unknown>(
 policyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocument>>,
          TError,
          Awaited<ReturnType<typeof getDocument>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = unknown>(
 policyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDocument<TData = Awaited<ReturnType<typeof getDocument>>, TError = unknown>(
 policyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocument>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentQueryOptions(policyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type registerDocumentResponse200 = {
  data: PolicyDocumentResponse
  status: 200
}

export type registerDocumentResponseSuccess = (registerDocumentResponse200) & {
  headers: Headers;
};
;

export type registerDocumentResponse = (registerDocumentResponseSuccess)

export const getRegisterDocumentUrl = (policyId: string,) => {




  return `/api/v1/policies/${policyId}/document`
}

export const registerDocument = async (policyId: string,
    registerPolicyDocumentRequest: RegisterPolicyDocumentRequest, options?: Parameters<typeof customInstance>[1]): Promise<registerDocumentResponse> => {

  return customInstance<registerDocumentResponse>(getRegisterDocumentUrl(policyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerPolicyDocumentRequest)
  }
);}





export const getRegisterDocumentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerDocument>>, TError,{policyId: string;data: RegisterPolicyDocumentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerDocument>>, TError,{policyId: string;data: RegisterPolicyDocumentRequest}, TContext> => {

const mutationKey = ['registerDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerDocument>>, {policyId: string;data: RegisterPolicyDocumentRequest}> = (props) => {
          const {policyId,data} = props ?? {};

          return  registerDocument(policyId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof registerDocument>>>
    export type RegisterDocumentMutationBody = RegisterPolicyDocumentRequest
    export type RegisterDocumentMutationError = unknown

    export const useRegisterDocument = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerDocument>>, TError,{policyId: string;data: RegisterPolicyDocumentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerDocument>>,
        TError,
        {policyId: string;data: RegisterPolicyDocumentRequest},
        TContext
      > => {
      return useMutation(getRegisterDocumentMutationOptions(options), queryClient);
    }
    export type deleteDocumentResponse200 = {
  data: void
  status: 200
}

export type deleteDocumentResponseSuccess = (deleteDocumentResponse200) & {
  headers: Headers;
};
;

export type deleteDocumentResponse = (deleteDocumentResponseSuccess)

export const getDeleteDocumentUrl = (policyId: string,) => {




  return `/api/v1/policies/${policyId}/document`
}

export const deleteDocument = async (policyId: string, options?: Parameters<typeof customInstance>[1]): Promise<deleteDocumentResponse> => {

  return customInstance<deleteDocumentResponse>(getDeleteDocumentUrl(policyId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteDocumentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{policyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{policyId: string}, TContext> => {

const mutationKey = ['deleteDocument'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocument>>, {policyId: string}> = (props) => {
          const {policyId} = props ?? {};

          return  deleteDocument(policyId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocument>>>

    export type DeleteDocumentMutationError = unknown

    export const useDeleteDocument = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocument>>, TError,{policyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocument>>,
        TError,
        {policyId: string},
        TContext
      > => {
      return useMutation(getDeleteDocumentMutationOptions(options), queryClient);
    }
    export type generateUploadUrlResponse200 = {
  data: PresignedUploadResponse
  status: 200
}

export type generateUploadUrlResponseSuccess = (generateUploadUrlResponse200) & {
  headers: Headers;
};
;

export type generateUploadUrlResponse = (generateUploadUrlResponseSuccess)

export const getGenerateUploadUrlUrl = (policyId: string,) => {




  return `/api/v1/policies/${policyId}/document/presigned-upload`
}

export const generateUploadUrl = async (policyId: string,
    presignedUploadRequest: PresignedUploadRequest, options?: Parameters<typeof customInstance>[1]): Promise<generateUploadUrlResponse> => {

  return customInstance<generateUploadUrlResponse>(getGenerateUploadUrlUrl(policyId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(presignedUploadRequest)
  }
);}





export const getGenerateUploadUrlMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateUploadUrl>>, TError,{policyId: string;data: PresignedUploadRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof generateUploadUrl>>, TError,{policyId: string;data: PresignedUploadRequest}, TContext> => {

const mutationKey = ['generateUploadUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateUploadUrl>>, {policyId: string;data: PresignedUploadRequest}> = (props) => {
          const {policyId,data} = props ?? {};

          return  generateUploadUrl(policyId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GenerateUploadUrlMutationResult = NonNullable<Awaited<ReturnType<typeof generateUploadUrl>>>
    export type GenerateUploadUrlMutationBody = PresignedUploadRequest
    export type GenerateUploadUrlMutationError = unknown

    export const useGenerateUploadUrl = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateUploadUrl>>, TError,{policyId: string;data: PresignedUploadRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateUploadUrl>>,
        TError,
        {policyId: string;data: PresignedUploadRequest},
        TContext
      > => {
      return useMutation(getGenerateUploadUrlMutationOptions(options), queryClient);
    }
