/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  PolicyDocumentResponse,
  PresignedUploadResponse
} from '../../model';


export const getGetDocumentResponseMock = (overrideResponse: Partial<Extract<PolicyDocumentResponse, object>> = {}): PolicyDocumentResponse => ({policyId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), originalFilename: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), contentType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sizeBytes: faker.helpers.arrayElement([faker.number.int(), undefined]), downloadUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getRegisterDocumentResponseMock = (overrideResponse: Partial<Extract<PolicyDocumentResponse, object>> = {}): PolicyDocumentResponse => ({policyId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), originalFilename: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), contentType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sizeBytes: faker.helpers.arrayElement([faker.number.int(), undefined]), downloadUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getGenerateUploadUrlResponseMock = (overrideResponse: Partial<Extract<PresignedUploadResponse, object>> = {}): PresignedUploadResponse => ({storageKey: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uploadUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

