/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PageProductResponse,
  ProductResponse
} from '../../model';

import {
  getCreateProductResponseMock,
  getGetProductResponseMock,
  getListProductsResponseMock,
  getUpdateProductResponseMock
} from './product-controller.faker';

export { getGetProductResponseMock, getUpdateProductResponseMock, getListProductsResponseMock, getCreateProductResponseMock } from './product-controller.faker';


export const getGetProductMockHandler = (overrideResponse?: ProductResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProductResponse> | ProductResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/products/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProductResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateProductMockHandler = (overrideResponse?: ProductResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ProductResponse> | ProductResponse), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/products/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateProductResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListProductsMockHandler = (overrideResponse?: PageProductResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PageProductResponse> | PageProductResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/products', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListProductsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateProductMockHandler = (overrideResponse?: ProductResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProductResponse> | ProductResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/products', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateProductResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeactivateProductMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/products/:id/lifecycle/deactivate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getActivateProductMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/products/:id/lifecycle/activate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getProductControllerMock = () => [
  getGetProductMockHandler(),
  getUpdateProductMockHandler(),
  getListProductsMockHandler(),
  getCreateProductMockHandler(),
  getDeactivateProductMockHandler(),
  getActivateProductMockHandler()
]
