spring:
  application:
    name: anverraglobal-backend
  
  # Spring Modulith configurations
  modulith:
    events:
      jdbc:
        # schema initialization should be managed via Flyway in production

  # Flyway core configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
