spring:
  application:
    name: anverraglobal-backend
  profiles:
    active: local
  
  # Spring Modulith configurations
  modulith:
    events:
      jdbc:
        # schema initialization should be managed via Flyway in production

  # Flyway core configuration
  flyway:
    enabled: true
    baseline-on-migrate: true

anverra:
  security:
    oauth2:
      issuer-uri: ${AUTH0_ISSUER_URI:https://dev-anverra.us.auth0.com/}
      audience: ${AUTH0_AUDIENCE:https://anverra-dev-api/}
