/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCustomerRequest,
  CustomerResponse,
  ListCustomersParams,
  PageCustomerResponse,
  UpdateCustomerRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCustomerResponse200 = {
  data: CustomerResponse
  status: 200
}

export type getCustomerResponseSuccess = (getCustomerResponse200) & {
  headers: Headers;
};
;

export type getCustomerResponse = (getCustomerResponseSuccess)

export const getGetCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

export const getCustomer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<getCustomerResponse> => {

  return customInstance<getCustomerResponse>(getGetCustomerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCustomerQueryKey = (id: string,) => {
    return [
    `/api/v1/customers/${id}`
    ] as const;
    }


export const getGetCustomerQueryOptions = <TData = Awaited<ReturnType<typeof getCustomer>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCustomerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomer>>> = ({ signal }) => getCustomer(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCustomer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCustomerQueryResult = NonNullable<Awaited<ReturnType<typeof getCustomer>>>
export type GetCustomerQueryError = unknown


export function useGetCustomer<TData = Awaited<ReturnType<typeof getCustomer>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomer>>,
          TError,
          Awaited<ReturnType<typeof getCustomer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomer<TData = Awaited<ReturnType<typeof getCustomer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomer>>,
          TError,
          Awaited<ReturnType<typeof getCustomer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomer<TData = Awaited<ReturnType<typeof getCustomer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCustomer<TData = Awaited<ReturnType<typeof getCustomer>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomer>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCustomerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateCustomerResponse200 = {
  data: CustomerResponse
  status: 200
}

export type updateCustomerResponseSuccess = (updateCustomerResponse200) & {
  headers: Headers;
};
;

export type updateCustomerResponse = (updateCustomerResponseSuccess)

export const getUpdateCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

export const updateCustomer = async (id: string,
    updateCustomerRequest: UpdateCustomerRequest, options?: Parameters<typeof customInstance>[1]): Promise<updateCustomerResponse> => {

  return customInstance<updateCustomerResponse>(getUpdateCustomerUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCustomerRequest)
  }
);}





export const getUpdateCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: string;data: UpdateCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: string;data: UpdateCustomerRequest}, TContext> => {

const mutationKey = ['updateCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCustomer>>, {id: string;data: UpdateCustomerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCustomer(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof updateCustomer>>>
    export type UpdateCustomerMutationBody = UpdateCustomerRequest
    export type UpdateCustomerMutationError = unknown

    export const useUpdateCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: string;data: UpdateCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCustomer>>,
        TError,
        {id: string;data: UpdateCustomerRequest},
        TContext
      > => {
      return useMutation(getUpdateCustomerMutationOptions(options), queryClient);
    }
    export type listCustomersResponse200 = {
  data: PageCustomerResponse
  status: 200
}

export type listCustomersResponseSuccess = (listCustomersResponse200) & {
  headers: Headers;
};
;

export type listCustomersResponse = (listCustomersResponseSuccess)

export const getListCustomersUrl = (params: ListCustomersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/customers?${stringifiedParams}` : `/api/v1/customers`
}

export const listCustomers = async (params: ListCustomersParams, options?: Parameters<typeof customInstance>[1]): Promise<listCustomersResponse> => {

  return customInstance<listCustomersResponse>(getListCustomersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCustomersQueryKey = (params?: ListCustomersParams,) => {
    return [
    `/api/v1/customers`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCustomersQueryOptions = <TData = Awaited<ReturnType<typeof listCustomers>>, TError = unknown>(params: ListCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCustomersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCustomers>>> = ({ signal }) => listCustomers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCustomers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCustomersQueryResult = NonNullable<Awaited<ReturnType<typeof listCustomers>>>
export type ListCustomersQueryError = unknown


export function useListCustomers<TData = Awaited<ReturnType<typeof listCustomers>>, TError = unknown>(
 params: ListCustomersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCustomers>>,
          TError,
          Awaited<ReturnType<typeof listCustomers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCustomers<TData = Awaited<ReturnType<typeof listCustomers>>, TError = unknown>(
 params: ListCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCustomers>>,
          TError,
          Awaited<ReturnType<typeof listCustomers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCustomers<TData = Awaited<ReturnType<typeof listCustomers>>, TError = unknown>(
 params: ListCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListCustomers<TData = Awaited<ReturnType<typeof listCustomers>>, TError = unknown>(
 params: ListCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCustomers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCustomersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createCustomerResponse200 = {
  data: CustomerResponse
  status: 200
}

export type createCustomerResponseSuccess = (createCustomerResponse200) & {
  headers: Headers;
};
;

export type createCustomerResponse = (createCustomerResponseSuccess)

export const getCreateCustomerUrl = () => {




  return `/api/v1/customers`
}

export const createCustomer = async (createCustomerRequest: CreateCustomerRequest, options?: Parameters<typeof customInstance>[1]): Promise<createCustomerResponse> => {

  return customInstance<createCustomerResponse>(getCreateCustomerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCustomerRequest)
  }
);}





export const getCreateCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext> => {

const mutationKey = ['createCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCustomer>>, {data: CreateCustomerRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCustomer(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof createCustomer>>>
    export type CreateCustomerMutationBody = CreateCustomerRequest
    export type CreateCustomerMutationError = unknown

    export const useCreateCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCustomer>>,
        TError,
        {data: CreateCustomerRequest},
        TContext
      > => {
      return useMutation(getCreateCustomerMutationOptions(options), queryClient);
    }
    export type deactivateCustomerResponse200 = {
  data: void
  status: 200
}

export type deactivateCustomerResponseSuccess = (deactivateCustomerResponse200) & {
  headers: Headers;
};
;

export type deactivateCustomerResponse = (deactivateCustomerResponseSuccess)

export const getDeactivateCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}/lifecycle/deactivate`
}

export const deactivateCustomer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<deactivateCustomerResponse> => {

  return customInstance<deactivateCustomerResponse>(getDeactivateCustomerUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getDeactivateCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateCustomer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateCustomer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deactivateCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateCustomer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deactivateCustomer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateCustomer>>>

    export type DeactivateCustomerMutationError = unknown

    export const useDeactivateCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateCustomer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateCustomer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeactivateCustomerMutationOptions(options), queryClient);
    }
    export type activateCustomerResponse200 = {
  data: void
  status: 200
}

export type activateCustomerResponseSuccess = (activateCustomerResponse200) & {
  headers: Headers;
};
;

export type activateCustomerResponse = (activateCustomerResponseSuccess)

export const getActivateCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}/lifecycle/activate`
}

export const activateCustomer = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<activateCustomerResponse> => {

  return customInstance<activateCustomerResponse>(getActivateCustomerUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getActivateCustomerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateCustomer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activateCustomer>>, TError,{id: string}, TContext> => {

const mutationKey = ['activateCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateCustomer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  activateCustomer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof activateCustomer>>>

    export type ActivateCustomerMutationError = unknown

    export const useActivateCustomer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateCustomer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateCustomer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getActivateCustomerMutationOptions(options), queryClient);
    }
