/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CustomerResponse,
  PageCustomerResponse
} from '../../model';

import {
  getCreateCustomerResponseMock,
  getGetCustomerResponseMock,
  getListCustomersResponseMock,
  getUpdateCustomerResponseMock
} from './customer-controller.faker';

export { getGetCustomerResponseMock, getUpdateCustomerResponseMock, getListCustomersResponseMock, getCreateCustomerResponseMock } from './customer-controller.faker';


export const getGetCustomerMockHandler = (overrideResponse?: CustomerResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CustomerResponse> | CustomerResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/customers/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCustomerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateCustomerMockHandler = (overrideResponse?: CustomerResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CustomerResponse> | CustomerResponse), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/customers/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateCustomerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListCustomersMockHandler = (overrideResponse?: PageCustomerResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PageCustomerResponse> | PageCustomerResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/customers', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListCustomersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateCustomerMockHandler = (overrideResponse?: CustomerResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CustomerResponse> | CustomerResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/customers', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateCustomerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeactivateCustomerMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/customers/:id/lifecycle/deactivate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getActivateCustomerMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/customers/:id/lifecycle/activate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getCustomerControllerMock = () => [
  getGetCustomerMockHandler(),
  getUpdateCustomerMockHandler(),
  getListCustomersMockHandler(),
  getCreateCustomerMockHandler(),
  getDeactivateCustomerMockHandler(),
  getActivateCustomerMockHandler()
]
